### ISSUE TITLE
Specification title is missing

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#1]
![1](https://cloud.githubusercontent.com/assets/12176352/25701762/9bbd4e1c-3082-11e7-8df2-44ea4e1e01f0.png)

**Comment by jayaprakashwhirl** [comment]
![screenshot from 2017-05-05 16-59-20](https://cloud.githubusercontent.com/assets/28391110/25743853/3cc935c8-31b4-11e7-88e8-b548ae9de9ab.png)

**Comment by jayaprakashwhirl** [comment]
![screenshot from 2017-05-05 18-41-59](https://cloud.githubusercontent.com/assets/28391110/25746794/9fd9e4c4-31c2-11e7-9c78-474309e36103.png)
