### ISSUE TITLE
Distribute the design area to the site width

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#10]
![7](https://cloud.githubusercontent.com/assets/12176352/25705152/311bc7dc-3091-11e7-81cb-9d4ad3f8190f.png)

**Comment by mano42023** [comment]
Design area is distriputed
![toolwidth](https://cloud.githubusercontent.com/assets/27298992/26195901/ea96e36e-3bda-11e7-8c6f-eb67180c64a3.png)
