### ISSUE TITLE
Change the product name to short

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#11]
![8](https://cloud.githubusercontent.com/assets/12176352/25705492/55771022-3092-11e7-9914-c39ffe86df1e.png)

**Comment by LisySamuel92** [comment]
I have shortened products name please confirm is it ok or not

![screen shot 2017-05-04 at 7 06 48 pm](https://cloud.githubusercontent.com/assets/28390513/25706068/000e1b88-30fd-11e7-9368-cf3d8a26239a.png)
