### ISSUE TITLE
Login with social media is not working

### ISSUE THREAD

**Issue by LisySamuel92** [whirldata/pjt1#12]
when trying to connect with facebook and twitter provides error.

![screen shot 2017-05-04 at 6 54 50 pm](https://cloud.githubusercontent.com/assets/28390513/25705573/5eb8c9f0-30fb-11e7-9dc4-b01ccb57ad92.png)

![screen shot 2017-05-04 at 6 57 16 pm](https://cloud.githubusercontent.com/assets/28390513/25705608/891747e4-30fb-11e7-9134-d97f70e82594.png)

![screen shot 2017-05-04 at 6 57 51 pm](https://cloud.githubusercontent.com/assets/28390513/25705625/9ea99300-30fb-11e7-9f1a-4040b7279abb.png)

**Comment by jayaprakashwhirl** [comment]
![fblogin](https://cloud.githubusercontent.com/assets/28391110/25798014/328bc35a-33fd-11e7-8074-bcf4ff026f7f.png)

**Comment by jayaprakashwhirl** [comment]
![twitterlogin](https://cloud.githubusercontent.com/assets/28391110/25798075/6168f01c-33fd-11e7-837b-06b859802591.png)
