### ISSUE TITLE
Button meshup in Simple product page

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#13]
![9](https://cloud.githubusercontent.com/assets/12176352/25707529/a57c2aca-3098-11e7-8cd3-0889e47fedb5.png)

**Comment by jayaprakashwhirl** [comment]
![screenshot from 2017-05-05 16-45-39](https://cloud.githubusercontent.com/assets/28391110/25743495/546c3560-31b2-11e7-924c-fd63b349d76c.png)
