### ISSUE TITLE
Product review submission does not working

### ISSUE THREAD

**Issue by LisySamuel92** [whirldata/pjt1#18]
Product review submission in PDP page does not responding.

![screen shot 2017-05-09 at 11 19 25 am](https://cloud.githubusercontent.com/assets/28390513/25837097/6cafbd0a-34a9-11e7-87b0-b6fdf174590b.png)

**Comment by jayaprakashwhirl** [comment]
![review1](https://cloud.githubusercontent.com/assets/28391110/25847001/d7738770-34d1-11e7-9c8d-d5ce12279a18.png)

**Comment by jayaprakashwhirl** [comment]
![review](https://cloud.githubusercontent.com/assets/28391110/25847007/e150495e-34d1-11e7-9892-8865d5008d04.png)
