### ISSUE TITLE
FB share does not share my design

### ISSUE THREAD

**Issue by LisySamuel92** [whirldata/pjt1#19]
FB share in designing page shares the template image of product it does not share my design of the product

![screen shot 2017-05-09 at 12 34 35 pm](https://cloud.githubusercontent.com/assets/28390513/25839103/eae1f850-34b3-11e7-8db7-759339ad732a.png)

**Comment by jayaprakashwhirl** [comment]
![fbshare](https://cloud.githubusercontent.com/assets/28391110/25850484/209bb55e-34e0-11e7-9b72-8f8232e6f0d5.png)
