### ISSUE TITLE
Change alertbox to Bootstrap modal window in PDP

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#2]
![2](https://cloud.githubusercontent.com/assets/12176352/25701833/ec823646-3082-11e7-8ff3-e3a355972d2b.png)

**Comment by jayaprakashwhirl** [comment]
i did this in dev server if it is ok i will change in UAT server
![screenshot from 2017-05-05 13-36-46](https://cloud.githubusercontent.com/assets/28391110/25738011/67d9d342-3198-11e7-8ee8-23de08f774c5.png)

**Comment by muthugit** [comment]
Change the text as
"Please enter the quantity more than Minimum Order Quantity(MoQ)"
