### ISSUE TITLE
Two no of Show drop down box presented in title bar 

### ISSUE THREAD

**Issue by LisySamuel92** [whirldata/pjt1#25]
Title bar of a page contains two no of  drop down box to shows per page

![screen shot 2017-05-12 at 11 49 45 am](https://cloud.githubusercontent.com/assets/28390513/25985628/24a9f252-3709-11e7-947f-b0e5b71e0418.png)

**Comment by jayaprakashwhirl** [comment]
![abc](https://cloud.githubusercontent.com/assets/28391110/25997003/ade35198-3737-11e7-8c14-51c819e0c931.png)

**Comment by mano42023** [comment]
One drop down bar is removed  


![showbarinplp](https://cloud.githubusercontent.com/assets/27298992/26201548/2b76e508-3bf1-11e7-997b-bb1aac337050.png)
