### ISSUE TITLE
Less amount of details shown in PDP page

### ISSUE THREAD

**Issue by LisySamuel92** [whirldata/pjt1#30]
![screen shot 2017-05-12 at 5 08 36 pm](https://cloud.githubusercontent.com/assets/28390513/25996610/c9149ea6-3735-11e7-9ed4-fdc9f52fcf32.png)

**Comment by jayaprakashwhirl** [comment]
If we add description in the time of product creating that details show correctly
![details](https://cloud.githubusercontent.com/assets/28391110/25996819/c8d1a686-3736-11e7-8c88-ff4393232668.png)
