### ISSUE TITLE
MOQ did not display in PDP page

### ISSUE THREAD

**Issue by LisySamuel92** [whirldata/pjt1#31]
MOQ did not display in PDP page and when i click customize button it displays dialogue box to enter quantity even i enter 1000 in as quantity

![screen shot 2017-05-16 at 11 39 17 am](https://cloud.githubusercontent.com/assets/28390513/26092167/03a37bb0-3a2d-11e7-93f9-3e3093173996.png)

![screen shot 2017-05-16 at 11 39 35 am](https://cloud.githubusercontent.com/assets/28390513/26092173/0879cee6-3a2d-11e7-8077-02137456f35f.png)

**Comment by jayaprakashwhirl** [comment]
![moq](https://cloud.githubusercontent.com/assets/28391110/26104717/c34de840-3a5c-11e7-854c-5fb1217c2615.png)
