### ISSUE TITLE
Conflict in the filter dropdown

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#32]
Two different dropdown appearing.
Example page: http://172.104.45.18/dilsebol2/drinkware/coffeemugs.html
![filters](https://cloud.githubusercontent.com/assets/12176352/26135181/bf5cdad2-3a68-11e7-8d2b-1e4962496a3e.PNG)

**Comment by LisySamuel92** [comment]
I already raise this bug ji please close this
