### ISSUE TITLE
Product title not appearing in PLP

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#33]
Product title not showing in PDP.
![product-title](https://cloud.githubusercontent.com/assets/12176352/26135227/11bf9350-3a69-11e7-9795-980a5d37e0d5.PNG)

**Comment by LisySamuel92** [comment]
Product title displayed now

![screen shot 2017-05-18 at 1 28 13 pm](https://cloud.githubusercontent.com/assets/28390513/26192086/faba77a4-3bcd-11e7-87a9-3dd61394b2f5.png)
