### ISSUE TITLE
Wrong image in the product catalog

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#34]
T-shirt image should be replaced to Mug
![mug](https://cloud.githubusercontent.com/assets/12176352/26135269/4410084e-3a69-11e7-83ce-85192259e283.PNG)

**Comment by LisySamuel92** [comment]
Relevant image are set to the product

![screen shot 2017-05-18 at 10 56 23 am](https://cloud.githubusercontent.com/assets/28390513/26187756/db63ead0-3bb8-11e7-939d-4360fb9b5497.png)
