### ISSUE TITLE
No image found in PLP

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#35]
Appropriate images to be uploaded
![no images](https://cloud.githubusercontent.com/assets/12176352/26135338/b5c8e6a4-3a69-11e7-898b-ca3b668012f0.PNG)

**Comment by LisySamuel92** [comment]
Images are shown

![screen shot 2017-05-18 at 10 54 02 am](https://cloud.githubusercontent.com/assets/28390513/26187679/5a2ca966-3bb8-11e7-8bbc-69e6816851dc.png)
