### ISSUE TITLE
Required quantity title is missing

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#36]
Required quantity title is missing. 
#1. Add title
#2. Add placeholder for the textbox

![qty-title](https://cloud.githubusercontent.com/assets/12176352/26142842/3981923e-3a97-11e7-86c2-879a8b59f5f8.PNG)

**Comment by LisySamuel92** [comment]
Title for quantity and place holder added

![screen shot 2017-05-18 at 1 24 02 pm](https://cloud.githubusercontent.com/assets/28390513/26191891/4d07eeb6-3bcd-11e7-8b0c-050fa50becbd.png)

![screen shot 2017-05-18 at 1 24 31 pm](https://cloud.githubusercontent.com/assets/28390513/26191912/665c1ea0-3bcd-11e7-9185-7ce4c9b31e72.png)
