### ISSUE TITLE
Bags category contains "Sample" sub category

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#37]
![bags-category](https://cloud.githubusercontent.com/assets/12176352/26142964/b77cff84-3a97-11e7-8a1c-1ee4405680a0.PNG)

**Comment by LisySamuel92** [comment]
Bags does not have category so i just delete it 

![screen shot 2017-05-17 at 6 48 47 pm](https://cloud.githubusercontent.com/assets/28390513/26155688/b2bacba8-3b31-11e7-8a35-d109cc445e38.png)
