### ISSUE TITLE
Featured products contains No image, no title and no price

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#38]
![featured-products](https://cloud.githubusercontent.com/assets/12176352/26143014/f0f2737a-3a97-11e7-9f95-0b8e05e35adb.PNG)

**Comment by LisySamuel92** [comment]
I added the products ids and it displays image and name when hovered

![screen shot 2017-05-17 at 6 55 11 pm](https://cloud.githubusercontent.com/assets/28390513/26155995/879594f2-3b32-11e7-937f-bc9f4130276d.png)
