### ISSUE TITLE
Blur image on PDP

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#39]
When I click the thumbnail image, it shows blurred image
![imageblur](https://cloud.githubusercontent.com/assets/12176352/26143080/3f447c94-3a98-11e7-823a-759eb481df41.PNG)

**Comment by mano42023** [comment]
Blur image on PDP issue is resolved 

![blurimg3](https://cloud.githubusercontent.com/assets/27298992/26189989/dc07df80-3bc4-11e7-953c-6140b7df5496.png)
![blurimag2](https://cloud.githubusercontent.com/assets/27298992/26189988/dc050c38-3bc4-11e7-9eb0-a0737da5c709.png)
![blurimage](https://cloud.githubusercontent.com/assets/27298992/26189987/dc04ee06-3bc4-11e7-8c1e-f3666ba97867.png)
