### ISSUE TITLE
No color option is showing

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#5]
![5](https://cloud.githubusercontent.com/assets/12176352/25702082/375435ce-3084-11e7-851e-effbfe55a3e7.png)

**Comment by mano42023** [comment]
Colour option is now correctly showing for configurable products.
![coloroption](https://cloud.githubusercontent.com/assets/27298992/26191399/5ae0f19c-3bcb-11e7-9ffa-e1999042151a.png)
