### ISSUE TITLE
Remove category for the design

### ISSUE THREAD

**Issue by muthugit** [whirldata/pjt1#7]
Please remove the design category in all relevant pages
![6](https://cloud.githubusercontent.com/assets/12176352/25702161/9f55db46-3084-11e7-9304-b223efa62230.png)

**Comment by mano42023** [comment]
Category is removed from design 
![categoryremovedintool](https://cloud.githubusercontent.com/assets/27298992/26190902/553c7754-3bc9-11e7-9b01-338e895379b3.png)
tool page
