### ISSUE TITLE
In print order shows travel denizen logo not dilsebol logo

### ISSUE THREAD

**Issue by jayaprakashwhirl** [whirldata/pjt1#74]
![print](https://cloud.githubusercontent.com/assets/28391110/26155928/69b58ca8-3b32-11e7-9915-20fad162797b.png)
 and
![traveldenizen](https://cloud.githubusercontent.com/assets/28391110/26155948/72978dd0-3b32-11e7-8dc7-2bf305265298.png)

**Comment by LisySamuel92** [comment]
changed the logo in print order
