### ISSUE TITLE
In configurable products except t-shirts contain 2 input box and conflict in customize

### ISSUE THREAD

**Issue by LisySamuel92** [whirldata/pjt1#79]
![screen shot 2017-05-18 at 11 09 18 am](https://cloud.githubusercontent.com/assets/28390513/26188055/a3f4e89a-3bba-11e7-818a-910ffa675ecc.png)

![screen shot 2017-05-18 at 11 10 51 am](https://cloud.githubusercontent.com/assets/28390513/26188062/b2c6f750-3bba-11e7-92f8-f39736628027.png)

**Comment by mano42023** [comment]
![twoinputfield](https://cloud.githubusercontent.com/assets/27298992/26199802/01abc12e-3be9-11e7-9e8b-3d863e57dc6d.png)
Text field removed
