### ISSUE TITLE
Unwanted click button in Tool Page

### ISSUE THREAD

**Issue by LisySamuel92** [whirldata/pjt1#80]
![screen shot 2017-05-18 at 11 23 43 am](https://cloud.githubusercontent.com/assets/28390513/26188421/b3ca0a1e-3bbc-11e7-958a-a4beb19d0090.png)

**Comment by mano42023** [comment]
Click button removed
![clikbutton](https://cloud.githubusercontent.com/assets/27298992/26199643/74318b9e-3be8-11e7-8058-5a04cc8e4549.png)
